[package]
name = "obfuscat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bytesize = "1.3.0"
clap = { version = "4.5.21", features = ["derive"] }
clap-verbosity-flag = "3.0.0"
env_logger = "0.11.5"
gix-attributes = { version = "0.23.1", features = ["serde"] }
git2 = "0.19.0"
glob = "0.3.1"
itertools = "0.13.0"
log = "0.4.22"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
url = { version = "2.5.4", features = ["serde"] }
