[package]
name = "git-file-storage"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "git-gfs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.93"
bytesize = "1.3.0"
clap = { version = "4.5.21", features = ["derive"] }
clap-verbosity-flag = "3.0.0"
env_logger = "0.11.5"
glob = "0.3.1"
itertools = "0.13.0"
log = "0.4.22"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
url = { version = "2.5.4", features = ["serde"] }
gix = "0.68.0"
gix-filter = "0.15.0"
derive_more = { version = "1.0.0", features = ["full"] }
tar = "0.4.43"
xz = "0.1.0"
range-split = "0.4.0"
prng_split = "0.1.0"
scopeguard = "1.2.0"

[lints.clippy]
pedantic = "warn"

[dev-dependencies]
assert_cmd = "2.0.16"
copy_dir = "0.1.3"
predicates = "3.1.2"
temp-dir = "0.1.14"
rand = "0.8.5"
