[package]
name = "obfuscat"
version = "0.1.0"
edition = "2021"

[dependencies]
bytesize = "1.3.0"
clap = { version = "4.5.21", features = ["derive"] }
clap-verbosity-flag = "3.0.0"
env_logger = "0.11.5"
git2 = "0.19.0"
glob = "0.3.1"
log = "0.4.22"
serde = { version = "1.0.215", features = ["derive"] }
sha2 = "0.10.8"
